name: june
description: "June is a lightweight and modern state management library that focuses on providing a pattern very similar to Flutter's native state management."
version: 1.0.2
homepage: https://github.com/melodysdreamj/june

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
